* where my Emacs starts


After strugling with Emacs configuration for such a long time, I am into
spacemacs which combines the best part of Emacs an Vim. Actually, I
learnt how to use Vim by using spacemacs.

Right now, I use Emacs as my superIDE because of Spacemacs

* split the org settings

I use Org almost every day. As time goes by, the settings grows. There
are tons of emacs-elisp in my config.el related with Org. So I split the code in
config.el into several layers:
1. *zclorgbasic* layer which stores the basic setting for org including
   the global hotkey.
2. *zclorggtd*  layer which stores the settings for GTD using org; 
3. *zclorgexport* layer which stores the settings for exporting the org
   file as html, pdf, markdown
4. *zclorgpublish* layer which stores the settings for publishing the org
   file as a static website
5. *zclorggraph*  layer which stores the settings for using ditta and
   graphic (the two famous java package)
6. *zcljournal* layer describes my journaling system which keep track of
   my work.

Enjoy!
