#+title: make STEAM clear
#+setupfile: ~/Dropbox/zorg/org-templates/enpost.org
#+OPTIONS: d:figure,sub-problem,bibli,prefix,suffix

* Videos                                :video:
:LOGBOOK:
CLOCK: [2019-10-20 Sun 17:06]--[2019-10-20 Sun 17:23] =>  0:17
CLOCK: [2019-10-09 Wed 22:09]--[2019-10-20 Sun 17:03] => 258:54
CLOCK: [2019-10-07 Mon 09:49]--[2019-10-09 Wed 22:09] => 60:20
CLOCK: [2019-10-06 Sun 23:34]--[2019-10-07 Mon 09:48] => 10:14
CLOCK: [2019-10-06 Sun 19:56]--[2019-10-06 Sun 22:44] =>  2:48
CLOCK: [2019-10-06 Sun 19:54]--[2019-10-06 Sun 19:56] =>  0:02
CLOCK: [2019-10-06 Sun 11:11]--[2019-10-06 Sun 19:54] =>  8:43
CLOCK: [2019-10-06 Sun 09:27]--[2019-10-06 Sun 11:11] =>  1:44
CLOCK: [2019-10-06 Sun 09:16]--[2019-10-06 Sun 09:27] =>  0:11
CLOCK: [2019-10-06 Sun 08:33]--[2019-10-06 Sun 09:16] =>  0:43
CLOCK: [2019-10-06 Sun 08:21]--[2019-10-06 Sun 08:33] =>  0:12
:END:
[2019-10-05 Sat 16:52]


** TODO video 1
:PROPERTIES:
:EXPORT_FILE_NAME: index
:LATEX_TITLE: video 1
:EXPORT_HUGO_SECTION: publication
:EXPORT_HUGO_BUNDLE: video-1
:EXPORT_DESCRIPTION: summary of this post
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :projects '("project-my-workflow-of-creating-a-video")
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "youtube") (icon_pack . "fab")  (name . "Watch it")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "instagram") (icon_pack . "fab")  (name . "Inst")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "weibo") (icon_pack . "fab")  (name . "Weibo")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "wechat") (icon_pack . "fab")  (name . "Wechat")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "github") (icon_pack . "fab")  (name . "Source")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "file-pdf") (icon_pack . "fas")  (name . "Source")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "slideshare") (icon_pack . "fas")  (name . "Slides")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "twitter") (icon_pack . "fab")  (name . "Follow")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "facebook") (icon_pack . "fab")  (name . "Follow")  (url . "/course/example/" ) )
:END:
:LOGBOOK:
CLOCK: [2020-02-01 Sat 11:54]--[2020-02-01 Sat 11:55] =>  0:01
:END:
<2020-02-01 Sat 11:54>


* Posts
[2019-10-05 Sat 16:52]


** TODO Export Markdown and latex using Emacs Org :Emacs:Org:Hugo:LaTeX:Markdown:
:PROPERTIES:
:EXPORT_HUGO_SECTION: post
:EXPORT_HUGO_BUNDLE: export-markdown-and-latex-using-emacs-org
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :projects '("my-workflow-of-creating-a-video")
:EXPORT_DESCRIPTION: set up the Emacs org and ox-hugo to export the org files in markdown and latex format.
:EXPORT_FILE_NAME: index
:END:
:LOGBOOK:
CLOCK: [2019-12-07 Sat 07:46]--[2019-12-07 Sat 07:48] =>  0:02
:END:
<2019-12-07 Sat 07:46>

#+include: "./post/tool/export-markdown-and-latex-using-emacs-org.org"

** TODO Drawing Graphs Using TikZ in Emacs Org  :Emacs:Org:TikZ:LaTeX:
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_SECTION: post
:VISIBILITY: folded
:EXPORT_HUGO_BUNDLE: drawing-graphs-using-tikz-in-emacs-org
:EXPORT_DESCRIPTION: This post collects working examples of drawing graphs using TikZ in Emacs Org
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :projects '("my-workflow-of-creating-a-video")
:END:
:LOGBOOK:
CLOCK: [2019-12-08 Sun 17:30]--[2019-12-08 Sun 17:33] =>  0:03
:END:
<2019-12-08 Sun 17:30>

{{{titlepage(example3)}}}

# setup the tikz in emacs Org mode
#+include: "./post/tool/set-up-the-tikz-in-emacs-org-mode.org"
# draw graphs using tikz in emacs Org mode
#+include: "./post/tool/draw-graphs-using-tikz-in-emacs-org.org"

** TODO Signals and Systems Chapter 1 Problems Part 1 (1.1-1.20) :SignalsAndSystems:
:PROPERTIES:
:EXPORT_FILE_NAME: index
:LATEX_TITLE: Signal and System Chapter 1 Problems
:EXPORT_HUGO_SECTION: post
:EXPORT_HUGO_BUNDLE: signal-and-system-chapter-1-problems-part-1--1-dot-1-1-dot-21
:EXPORT_DESCRIPTION: This post consists of solutions to problems from 1.1 to 1.21 in chapter 1 of the book Signals and Systems by Oppenheim ,Willsky and Nawab.
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :projects '("project-solution-manual-of-signals-and-systems-by-oppenheim")
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "github") (icon_pack . "fab")  (name . "Source")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "file-pdf") (icon_pack . "fas")  (name . "Source")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "slideshare") (icon_pack . "fas")  (name . "Slides")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "youtube") (icon_pack . "fab")  (name . "Watch it")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "instagram") (icon_pack . "fab")  (name . "Inst")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "weibo") (icon_pack . "fab")  (name . "Weibo")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "wechat") (icon_pack . "fab")  (name . "Wechat")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "twitter") (icon_pack . "fab")  (name . "Follow")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "facebook") (icon_pack . "fab")  (name . "Follow")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "reddit") (icon_pack . "fab")  (name . "listen")  (url . "/course/example/" ) )
:END:
<2020-01-02 Thu 23:32>

{{{titlepage(eulerEquation)}}}

#+include: "./post/technology/SignalsAndSystems/Chapter1BasicProblems1.org"

** TODO Signals and Systems Chapter 1 Problems Part 2 (1.21-1.31) :SignalsAndSystems:
:PROPERTIES:
:EXPORT_FILE_NAME: index
:LATEX_TITLE: Signals and System Chapter 1 Problems Part 2 (1.21-1.31)
:EXPORT_HUGO_SECTION: post
:EXPORT_HUGO_BUNDLE: signals-and-system-chapter-1-problems-part-2--1-dot-21-1-dot-31
:EXPORT_DESCRIPTION: This post consists of solutions to problems from 1.21 to 1.31 in chapter 1 of the book Signals and Systems by Oppenheim ,Willsky and Nawab.cite:oppenheim_signals_1997
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :projects '("project-solution-manual-of-signals-and-systems-by-oppenheim")
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "youtube") (icon_pack . "fab")  (name . "Watch it")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "instagram") (icon_pack . "fab")  (name . "Inst")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "weibo") (icon_pack . "fab")  (name . "Weibo")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "wechat") (icon_pack . "fab")  (name . "Wechat")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "github") (icon_pack . "fab")  (name . "Source")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "file-pdf") (icon_pack . "fas")  (name . "Source")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "slideshare") (icon_pack . "fas")  (name . "Slides")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "twitter") (icon_pack . "fab")  (name . "Follow")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "facebook") (icon_pack . "fab")  (name . "Follow")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "reddit") (icon_pack . "fab")  (name . "listen")  (url . "/course/example/" ) )
:END:
:LOGBOOK:
CLOCK: [2020-02-01 Sat 16:02]--[2020-02-01 Sat 16:03] =>  0:01
:END:
<2020-02-01 Sat 16:02>

{{{titlepage(figProb1-21-0)}}}

#+include: "./post/technology/SignalsAndSystems/Chapter1BasicProblems2.org"

*** Reference

:bibli:
 bibliography:~/Dropbox/research_library/zcl.bib
 bibliographystyle:unsrt
:end:

** TODO Signals and Systems Chapter 1 Problems Part 3 (1.32-1.47) :SignalsAndSystems:
   :PROPERTIES:
   :EXPORT_FILE_NAME: index
   :LATEX_TITLE: Signals and Systems Chapter 1 Problems Part 3 (1.32-1.47)
   :EXPORT_HUGO_SECTION: post
   :EXPORT_HUGO_BUNDLE: signals-and-systems-chapter-1-problems-part-3--1-dot-32-1-dot-47
   :EXPORT_DESCRIPTION: This post consists of solutions to problems from 1.21 to 1.31 in chapter 1 of the book Signals and Systems by Oppenheim ,Willsky and Nawab.cite:oppenheim_signals_1997
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :projects '("project-solution-manual-of-signals-and-systems-by-oppenheim")
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "github") (icon_pack . "fab")  (name . "Source")  (url . "/course/example/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "file-pdf") (icon_pack . "fas")  (name . "Source")  (url . "/course/example/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "slideshare") (icon_pack . "fas")  (name . "Slides")  (url . "/course/example/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "youtube") (icon_pack . "fab")  (name . "Watch it")  (url . "/course/example/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "twitter") (icon_pack . "fab")  (name . "Follow")  (url . "/course/example/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "facebook") (icon_pack . "fab")  (name . "Follow")  (url . "/course/example/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "reddit") (icon_pack . "fab")  (name . "Listen")  (url . "/course/example/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "youtube") (icon_pack . "fab")  (name . "Watch it")  (url . "/course/example/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "instagram") (icon_pack . "fab")  (name . "Inst")  (url . "/course/example/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "weibo") (icon_pack . "fab")  (name . "Weibo")  (url . "/course/example/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "weixin") (icon_pack . "fab")  (name . "Weixin")  (url . "/course/example/" ) )
   :END:
 <2020-02-09 Sun 10:24>

*** Problem 1.32
    [2020-02-09 Sun 10:43]

    #+ATTR_LATEX: :options []{prob:1-32}
    #+NAME: prob:1-32
    #+begin_prob
    Let \(x(t)\) be a continuous-time signal, and let
    \begin{equation*}
    y_{1}(t) = x(2t) \ \mathrm{and} \ y_{2}(t) = x(t/2)
    \end{equation*}
    The signal \(y_{1}(t)\) represents a speeded up version of \(x(t)\) in the
    sense that the duration of the signal is cut in half. Similarly,
    \(y_{2}(t)\) represents a slowed down version of \(x(t)\) in the sense that
    the duration of the signal is doubled. Consider the following statements:

    a. If \(x(t)\) is periodic, then \(y_{1}(t)\) is periodic.
    b. If \(y_{1}(t)\) is periodic, then \(x(t)\) is periodic.
    c. If \(x(t)\) is periodic, then \(y_{2}(t)\) is periodic.
    d. If \(y_{2}(t)\) is periodic, then \(x(t)\) is periodic.

    For each of these statements, determine whether it is true, and if so,
    determine the relationship between the fundamental periods of the two
    signals considered in the statement. If the statement is not true, produce a
    counterexample to it.
    #+end_prob

:sub-problem:
*Problem 1.32a* <<Problem 1.32a>>

Let \(T\) be the fundamental period of \(x(t)\), then we have \(x(t+T) = x(t)\).
So \( y_{1}(t) = x(2t) = x(2t + T) = x(2(t+ \frac{T}{2} ))=
y_{1}(t+\frac{T}{2})\), \(y_{1}(t)\) is periodic and the fundamental period is
\( \frac{T}{2} \) which is consistent with our commonsense that \(y_{1}(t)\) is an
speeded up version of \(x(t)\).

:END:

:sub-problem:
*Problem 1.32b*

Let \(T\) be the fundamental period of \(y_{1}(t)\), then based on the analysis
of [[Problem 1.32a][Problem 1.32a]] , we have \(x(t)\) is a slowed down version of \(y_{1}(t)\),
hense \(x(t)\) is periodic and has fundamental period \(2T\).

:END:

:sub-problem:
*Problem 1.32c* <<Problem 1.32c>>

Let \(T\) be the fundamental period of \(x(t)\), then we have \(x(t+T) = x(t)\).
So \( y_{2}(t) = x(\tfrac{t}{2}) = x(\tfrac{t}{2} + T) = x(\frac{t+ 2T}{2})=
y_{2}(t+2T)\), \(y_{2}(t)\) is periodic and the fundamental period is
\(2T \) which is consistent with our commonsense that \(y_{2}(t)\) is an
slowed down version of \(x(t)\).

:END:

:sub-problem:
*Problem 1.32d*

Let \(T\) be the fundamental period of \(y_{2}(t)\), then based on the analysis
of [[Problem 1.32c][Problem 1.32c]] , we have \(x(t)\) is a speeded up version of \(y_{2}(t)\),
hense \(x(t)\) is periodic and has fundamental period \(\frac{T}{2}\).

:END:
*** Problem 1.33
    [2020-02-10 Mon 11:08]

    #+ATTR_LATEX: :options []{prob:1-33}
    #+NAME: prob:1-33
    #+begin_prob
    Let \(x[n]\) be a discrete-time signal, and let
    \begin{equation*}
    y_{1}[n] = x[2n] \ \mathrm{and}\ y_{2}[n] =
    \begin{cases}
    x[n/2], & n\ \mathrm{even} \\
    0, & n\ \mathrm{odd}
    \end{cases}
    \end{equation*}
    The signals \(y_{1}[n]\) and \(y_{2}[n]\) respectively represent in some
    sense the speeded  up and slowed down versions of \(x[n]\). However, it
    should be noted that the discrete-time notions of speeded up and slowed down
    have subtle differences with respect to their continuous-time counterparts.
    Consider the following statements:

    a. If \(x[n]\) is periodic, then \(y_{1}[n]\) is periodic.
    b. If \(y_{1}[n]\) is periodic, then \(x[n]\) is periodic.
    c. If \(x[n]\) is periodic, then \(y_{2}[n]\) is periodic.
    d. If \(y_{2}[n]\) is periodic, then \(x[n]\) is periodic.
    #+end_prob

:sub-problem:
*Problem 1.33a*

Let \(N\) be the fundamental period of \(x[n]\), then \(x[n+N] = x[n]\), and
\(y_{1}[n] = x[2n] = x[2n+N] = y_{1}[n+ \frac{N}{2}]\). If \(N\) is even, then
\(y_{1}[n]\) has fundamental period \(\frac{N}{2}\).  It is a little tricky
that when \(N\) is odd \(\frac{N}{2}\) has no meaning. If \(N\) is odd, we have
to express \(y_{1}[n] = x[2n] = x[2n+2N] = y_{1}[n+ N]\) hence \(y_{1}[n]\) has
fundamental period \(N\) if \(N\) is odd.
:END:
# b
:sub-problem:
*Problem 1.33b*

We can see \(y_{1}[n]\) is not only a speeded up version but also a down
sampling version of \(x[n]\). we cannot determine whether or not \(y_{1}[n]\)
is periodic based on that \(x[n]\) is periodic. We can only tell that the even
indexed value of \(x[n]\) is period. we know nothing about the odd indexed value
of \(x[n]\). An example is given below:

#+header: :file  "~/Dropbox/mstemc_hugo/static/img/tikz/figProb1-33b.pdf"
#+begin_src latex -n -r :results raw :exports none
\begin{tikzpicture}
\definecolor{mycolor}{RGB}{139,0,0}

\draw (-6.2,0)  -- (7.5,0)node[below] {$n$};
\draw (0,0) -- (0,2);
\foreach \x in {-6,-4,-2,...,6}
{
  \draw [mycolor,very thick] (\x,0) -- (\x,1);
  \draw[green,very thick] (\x+1,0) -- (\x+1, rand*2 ) node[at end, fill=green,shape=circle,minimum size=6pt,inner sep=0pt,outer sep=0pt]{} ;
  \draw[mycolor,fill=mycolor] (\x,1) circle[radius=3pt,] ;
}
\foreach \x in {-6,-5,...,7}
{
  \node[below=0.2cm] at (\x,0) {$\x$};
}
\node[right] at (0,1) {$1$};

\end{tikzpicture}
#+end_src

The given \(x[n]\) is periodic at \(2n\) but is random at \(2n+1\).
#+RESULTS:
[[file:~/Dropbox/mstemc_hugo/static/img/tikz/figProb1-33b.pdf]]


#+ATTR_HTML:  :width 80% :align center
#+ATTR_LATEX: :width 0.8\textwidth :align center
{{{if-latex(figProb1-33b.pdf,figProb1-33b.png)}}}

:END:

# c
:sub-problem:
*Problem 1.33c* <<Problem 1.33c>>

\(y_{2}[n]\) can treated as interpolation of \(x[n]\) with zero. So \(y_{2}[n]\)
is periodic with fundamental period \(2N\) where \(N\) is fundamental period of
\(x[n]\).

:END:

# d
:sub-problem:
*Problem 1.33d*

Based on analysis of [[Problem 1.33c][Problem 1.33c]] , \(y_{2}[n]\) has fundamental period \(2N\)
where \(N\) is the fundamental period of \(x[n]\).

Based on the fact that only integer is valid for the independent variable of
discrete-time signal, \(y_{2}[n]\) contains all the value of \(x[n]\) at the
even index whereas at the odd index \(y_{2}[n]= 0\).
:END:
*** Problem 1.34
    [2020-02-10 Mon 16:49]

    #+ATTR_LATEX: :options []{prob:1-34}
    #+NAME: prob:1-34
    #+begin_prob
    In this problem, we explore several of the properties of even and odd
    signals.

    a. Show that if \(x[n]\) is an odd signal, then
       \begin{equation*}
       \sum_{n=-\infty}^{+\infty} x[n] =0
       \end{equation*}
    b. Show that if \(x_{1}[n]\) is an odd signal and \(x_{2}[n]\) is an even
       signal, then \(x_{1}[n]x_{2}[n]\) is an odd signal.
    c. Let \(x[n]\) be an arbitrary signal with even and odd parts denoted by
       \begin{equation*}
       x_{e}[n] = \mathrm{Even}\{ x[n] \}
       \end{equation*}
       and
       \begin{equation*}
       x_{o}[n] = \mathrm{Odd} \{ x[n] \}
       \end{equation*}
       Show that
       \begin{equation*}
       \sum_{n=-\infty}^{+\infty} x^{2}[n] = \sum_{n=-\infty}^{+\infty} x_{e}^{2}[n] +  \sum_{n=-\infty}^{+\infty} x_{o}^{2}[n]
       \end{equation*}
    d. Although parts 1-3 have been stated in terms of discrete-time
       signals, the analogous properties are also valid in continuous time. To
       demonstrate this, show that
       \begin{equation*}
       \int_{-\infty}^{+\infty}x^{2}(t)dt = \int_{-\infty}^{+\infty} x_{e}^{2}(t)dt + \int_{-\infty}^{+\infty} x_{o}^{2}(t)dt
       \end{equation*}
       where \(x_{e}(t)\) and \(x_{o}(t)\) are, respectively, the even and odd
       parts of \(x(t)\).
    #+end_prob

# a
:sub-problem:
*Problem 1.34a*

If \(x[n]\) is an odd signal, then we have \(x[n] = -x[-n]\) and \(x[0]=0 \), so
\begin{eqnarray*}
\sum_{n=-\infty}^{+\infty} x[n] &=& \sum_{n=0}^{+\infty} x[n] + \sum_{-\infty}^{0} x[n] \\
&=& \sum_{n=0}^{\infty} \big( x[n] + x[-n] \big)  \\
&=& 0
\end{eqnarray*}
:END:
# b
:sub-problem:
*Problem 1.34b*

Because \(x_{1}[n]\) is an odd signal, \(x_{1}[n] = -x_{1}[-n]\). Because
\(x_{2}[n]\) is an even signal, \(x_{2}[n] = x_{2}[-n]\). we have

\begin{equation*}
x_{1}[n]x_{2}[n] = -x_{1}[-n]x_{2}[-n] \\
\end{equation*}

i.e. \(x_{1}[n]x_{2}[n]\) is an odd signal.
:END:
# c
:sub-problem:
*Problem 1.34c*

\begin{eqnarray*}
x_{e}[n] &=& \frac{x[n] + x[-n]}{2} \\
x_{o}[n] &=& \frac{x[n] - x[-n]}{2}
\end{eqnarray*}
Then we have
\begin{eqnarray*}
\sum_{n=-\infty}^{+\infty} x_{e}^{2}[n]  &=& \sum_{n=-\infty}^{+\infty} \bigg(  \frac{ x[n] + x[-n] }{2} \bigg)^{4}   \\
&=& \sum_{n=-\infty}^{+\infty} \bigg(  \frac{ x^{2}[n]  + x^{2}[-n] + 2x[n]x[-n]}{2} \bigg)
\end{eqnarray*}
\begin{eqnarray*}
\sum_{n=-\infty}^{+\infty} x_{o}^{2}[n]  &=& \sum_{n=-\infty}^{+\infty} \bigg(  \frac{ x[n] - x[-n] }{2} \bigg)^{2}   \\
&=& \sum_{n=-\infty}^{+\infty} \bigg(  \frac{ x^{2}[n]  + x^{2}[-n] - 2x[n]x[-n]}{4} \bigg)
\end{eqnarray*}
Then we add the above two equations and get
\begin{eqnarray*}
\sum_{n=-\infty}^{+\infty} x_{e}^{2}[n] +  \sum_{n=-\infty}^{+\infty} x_{o}^{2}[n]  &=& \sum_{n=-\infty}^{+\infty} \frac{x^{2}[n] + x^{2}[-n]}{2} \\
&=& \sum_{n=-\infty}^{+\infty} x^{2}[n]
\end{eqnarray*}

This conclusion tells us that even we seperate the signal into two parts(even
part and odd part), the sum of energy from the even part and odd part is the
total energy of the original signal.
:END:
# d
:sub-problem:
Let
\begin{eqnarray*}
\int_{-\infty}^{+\infty} x^{2}(t) dt &=& \int_{-\infty}^{+\infty} ( x_{e}(t) + x_{o}(t) )^{2}dt  \\
&=& \int_{-\infty}^{+\infty} x_{e}^{2}(t)dt + \int_{-\infty}^{+\infty} x_{o}^{2}(t) dt + \int_{-\infty}^{+\infty} x_{e}(t)x_{o}(t) dt \\
&=& \int_{-\infty}^{+\infty} x_{e}^{2}(t)dt + \int_{-\infty}^{+\infty} x_{o}^{2}(t) dt
\end{eqnarray*}

Notice that \(x_{e}(t)x_{o}(t)\) is and odd signal, so \(
\int_{-\infty}^{+\infty} x_{e}(t)x_{o}(t) dt = 0 \)
:END:
*** Problem 1.35
    [2020-02-10 Mon 19:50]

    #+ATTR_LATEX: :options []{prob:1-35}
    #+NAME: prob:1-35
    #+begin_prob
    Consider the periodic discrete-time exponential time signal
    \begin{equation*}
    x[n] = e^{im(2\pi/N)n}
    \end{equation*}
    Show that the fundamental period of this signal is
    \begin{equation*}
    N_{0} = N / \mathrm{gcd}(m,N)
    \end{equation*}
    where \(\mathrm{gcd}(m,N)\) is the greatest common divisor of \(m\) and
    \(N\)----that is, the largest integer that divides both \(m\) and \(N\) an
    integral number of times. For example,
    \begin{equation*}
    \mathrm{gcd}(2,1) = 1, \mathrm{gcd}(2,4) = 2, \mathrm{gcd}(8,12) = 4
    \end{equation*}
    Note that \(N_{0} = N\) if \(m\) and \(N\) have no factors in common.
    #+end_prob

#+ATTR_LATEX: :options []{}
#+begin_prf
Let \(N_{0}\) the fundamental period of \(x[n]\), so that
\begin{equation*}
m(2\pi / N) N_{0} = l\times 2\pi
\end{equation*}
So, we have \(N_{0} = \frac{lN}{m}\) . If \(m\) and \(N\) have no factors in
common, we have \(N_{0} = N\) when \(l = m\). If \(m\) and \(N\) have factors in
common, the fundamental period should be
\begin{equation*}
N_{0} = l \frac{N/ \mathrm{gcd}(m,N) }{m/ \mathrm{gcd}(m,N)}
\end{equation*}

When \(l = m/ \mathrm{gcd}(m,N) \), we have \(N_{0} = \frac{N}{ \mathrm{gcd}(m,N) }\).
#+end_prf
*** Problem 1.36
    [2020-02-11 Tue 09:55]

    #+ATTR_LATEX: :options []{prob:1-36}
    #+NAME: prob:1-36
    #+begin_prob
    Let \(x(t)\) be the continuous-time complex exponential signal:
    \begin{equation*}
    x(t) = e^{i\omega_{0}t}
    \end{equation*}
    with fundamental frequency \(\omega_{0}\) and fundamental period \(T_{0} =
    2\pi /\omega_{0}\). Consider the discrete-time signal obtained by taking
    equally spaced samples of \(x(t)\) --- that is,
    \begin{equation*}
    x[n] = x(nT) = e^{i\omega_{0}nT}
    \end{equation*}

    a. Show that \(x[n]\) is periodic if and only if \(T/T_{0}\) is a rational
       number -- that is, if and only if some multiple of the sampling interval
       exactly equals a multiple of the period of \(x(t)\).
    b. Suppose that \(x[n]\) is periodic --- that is, that
       \begin{equation}
       \label{eq:1-36-1}
       \frac{T}{T_{0}} = \frac{p}{q}
       \end{equation}
       where \(p\) and \(q\) are integers. What are the fundamental period and
       fundamental frequency of \(x[n]\)? Express the fundamental frequency as a
       fraction of \(\omega_{0}T\)
    c. Again assuming that \(T/T_{0}\) satisfies eq (\ref{eq:1-36-1}), determine
       precisely how many periods of \(x(t)\) are needed to obtain the samples
       that form a single period of \(x[n]\).
    #+end_prob

# a
:sub-problem:
*Problem 1.36a*

#+ATTR_LATEX: :options []{}
#+begin_prf
Let \(N\) the fundamental period of \(x[n]\), then we have
\begin{equation*}
\omega_{0} N T = 2\pi m
\end{equation*}
So \(N = \frac{2\pi m}{\omega_{0}T}\), We also have \( T_{0}=
\frac{2\pi}{\omega_{0}} \), then
\begin{equation*}
N = m\frac{T_{0}}{T}
\end{equation*}
Then \(\frac{T_{0}}{T}\) must be a rational number so that \(m\frac{T_{0}}{T}\)
is an integer and \(N\) could be an integer i.e. \(x[n]\) is periodic.
#+end_prf

:END:

# b
:sub-problem:
*Problem 1.36b*

Based on the analysis of Problem 1.36a, we have fundamental period of \(x[n]\)
\begin{equation*}
N = m\frac{T_{0}}{T} = m \frac{q}{p}
\end{equation*}
Where \(m\) is the minimum integer so that \(N\) is an integer. Based on the
conclusion of [[*Problem 1.35][Problem 1.35]] , we can re-express \(N\) as
\begin{equation*}
N = \frac{q}{\mathrm{gcd}(p,q)}
\end{equation*}
Where \(m = \frac{p}{\mathrm{gcd}(p,q)}\).
The fundamental frequency is
\begin{equation*}
\frac{2\pi}{N} = \frac{2\pi \mathrm{gcd}(p,q)}{q} = \omega_{0}T_{0} \frac{\mathrm{gcd}(p,q)}{q} = \omega_{0}T\frac{\mathrm{gcd}(p,q)}{p}
\end{equation*}

:END:

# c
:sub-problem:
*Problem 1.36c*

The fundamental period of \(x(t)\) is \(T_{0} = \frac{2\pi}{\omega_{0}}\) and
\(x[n]\) , \(N= \frac{q}{\mathrm{gcd}(p,q)}\). we have

\begin{equation*}
\frac{N}{T_{0}}= \frac{Np}{Tq} = \frac{q}{\mathrm{gcd}(p,q)T} \frac{p}{q} = \frac{p}{\mathrm{gcd}(p,q)T}
\end{equation*}
So, the discrete-time version of signal \(x(t)\) need at least
\(\frac{p}{\mathrm{gcd}(p,q)T}\) periods of \(x(t)\) to obtain one period of \(x[n]\).

:END:

:suffix:
Let's talk more about this problem. This problem preliminary discloses the concept
of sampling which is a main method of obtaining discrete-time signal from
continuous-time signal. Now let's put Nyquist's sampling theory aside and focus
on the sampling itself.

Suppose we have a continuous-time signal
\begin{equation*}
x(t) = \cos(4\pi t)
\end{equation*}
whose fundamental period is \(T_{0} = \frac{2\pi }{4\pi} = \frac{1}{2}\). Then
the sampling interval \(T\) must satisfies that \(T/T_{0}\) is a rational
number so that \(x[n]= x(nT)= \cos(4\pi nT )\) is a periodic signal.

Let \(T\), say, be \( \frac{1}{5} \), then
\begin{equation*}
\frac{T}{T_{0}} = \frac{2}{5}
\end{equation*}
The fundamental period of \(x[n]\) is \( N = \frac{q}{\mathrm{gcd}(p,q)} =
\frac{5}{\mathrm{gcd}(2,5)} = 5 \).

We can visualize \(x(t)\) and \(x[n]\) as below.

#+header: :file  "~/Dropbox/mstemc_hugo/static/img/tikz/figProb1-36-1.pdf"
#+begin_src latex -n -r :results raw :exports none
\begin{tikzpicture}
\definecolor{mycolor}{RGB}{139,0,0}
\begin{axis}[
axis lines = middle,
extra x ticks= {0,0.5,1.5,2.5,3.5,4.5,5.5},
]
\addplot[very thick,green,samples=300,domain = 0:6] {cos( deg( 4*pi*x ) )};
\addplot[ycomb,very thick,mycolor,mark=*,domain = 0:6,samples=7] {cos( deg( 4*pi/5*x ) )};
\end{axis}
\end{tikzpicture}
#+end_src

#+RESULTS:
[[file:~/Dropbox/mstemc_hugo/static/img/tikz/figProb1-36-1.pdf]]


#+ATTR_HTML:  :width 80% :align center
#+ATTR_LATEX: :width 0.8\textwidth :align center
{{{if-latex(figProb1-36-1.pdf,figProb1-36-1.png)}}}

From the above figure, we can see that the discrete-time signal \(x[n]\) has
fundamental period of \(5\) and its counterparts has fundamental period
\(\frac{1}{2}\). We need at least \(10\) period of \(x(t)\) to get one period of
\(x[n]\).

Now, if we take the Nyquist's sampling into consideration, we must sampling a
baseband signal with at least two times higher frequency of the signal to
recover the baseband signal without alias. i.e. we must sample \(x(t) =
\cos(4\pi t)\) with a signal of fundamental frequency \(8\pi\) to get signal
\(x[n] = \cos(8\pi n)\).

:END:
*** Problem 1.37
    [2020-02-11 Tue 16:42]

    #+ATTR_LATEX: :options []{prob:1-37}
    #+NAME: prob:1-37
    #+begin_prob
    An important concept in many communications applications in the correlation
    between two signals. In the problems at the end of Chapter 2, we will have
    more to say about this topic and will provide some indication of how it is
    used in practice. For now, we content ourselves with a brief introduction to
    correlation functions and some of their properties.

    Let \(x(t)\) and \(y(t)\) be two signals; then the correlation function is
    defined as
    \begin{equation*}
    \phi_{xy}(t) = \int_{-\infty}^{+\infty} x(t+ \tau) y(\tau)d\tau
    \end{equation*}

    The function \(\phi_{xx}(t)\) is usually referred to as the autocorrelation
    function of the signal \(x(t)\) , while \(\phi_{xy}(t)\) is often called a
    cross-correlation function.

    a. What is the relationship between \(\phi_{xy}(t)\) and \(\phi_{yx}(t)\) ?
    b. Compute the odd part of \(\phi_{xx}(t)\).
    c. Suppose that \(y(t)= x(t+ T)\). Express \(\phi_{xy}(t)\) and
       \(\phi_{yy}(t)\) in terms of \(\phi_{xx}(t)\).

    #+end_prob


* Projects    :project:
[2019-10-05 Sat 16:53]

** TODO my workflow of creating a video
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_BUNDLE: project-my-workflow-of-creating-a-video
:EXPORT_HUGO_SECTION: project
:EXPORT_DESCRIPTION: This collection of Videos and Posts describes my workflow of creating a video. Usage of some tools and methods are covered.
:END:

#+include: "./project/my-workflow-of-creating-a-video.org"

** TODO Solution Manual of Signals and Systems By Oppenheim
:PROPERTIES:
:EXPORT_FILE_NAME: index
:LATEX_TITLE: Solution Manual of Signals and Systems By Oppenheim
:EXPORT_HUGO_SECTION: project
:EXPORT_HUGO_BUNDLE: project-solution-manual-of-signals-and-systems-by-oppenheim
:EXPORT_DESCRIPTION: Solution manual of signals and systems by Oppenheim. All the problems are solved and many problems are visualized. During drawing the figures, I get a deep undertanding of concepts appearing in signals and systems. I hope this solution manual can help you achieve the same understanding.
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "youtube") (icon_pack . "fab")  (name . "Watch it")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "instagram") (icon_pack . "fab")  (name . "Inst")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "weibo") (icon_pack . "fab")  (name . "Weibo")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "wexin") (icon_pack . "fab")  (name . "Wexin")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "github") (icon_pack . "fab")  (name . "Source")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "file-pdf") (icon_pack . "fas")  (name . "Source")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "slideshare") (icon_pack . "fas")  (name . "Slides")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "twitter") (icon_pack . "fab")  (name . "Follow")  (url . "/course/example/" ) )
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "facebook") (icon_pack . "fab")  (name . "Follow")  (url . "/course/example/" ) )
:END:
:LOGBOOK:
CLOCK: [2020-02-01 Sat 16:09]--[2020-02-01 Sat 16:10] =>  0:01
:END:
<2020-02-01 Sat 16:09>


This is the solution manual of signals and systems by Oppenheim cite:oppenheim_signals_1997


bibliography:~/Dropbox/research_library/zcl.bib
bibliographystyle:unsrt


* Courses           :course:
[2019-10-05 Sat 16:53]

** TODO Solution Manual of Signals and Systems by Oppenheim :C_SignalsAndSystems:
   :PROPERTIES:
   :EXPORT_FILE_NAME: index
   :LATEX_TITLE: Solution Manual of Signals and Systems by Oppenheim etc.
   :EXPORT_HUGO_SECTION: project
   :EXPORT_HUGO_BUNDLE: course-solution-manual-of-signals-and-systems-by-oppenheim
   :EXPORT_DESCRIPTION: Collection of all the posts generated during figuring out all the problems in the textbook.
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :external_link /courses/signalsandsystemssolution
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "github") (icon_pack . "fab")  (name . "Source")  (url . "/course/signalsandsystemssolution/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "file-pdf") (icon_pack . "fas")  (name . "Docs")  (url . "/course/signalsandsystemssolution/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "slideshare") (icon_pack . "fas")  (name . "Slides")  (url . "/course/signalsandsystemssolution/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "youtube") (icon_pack . "fab")  (name . "Watch it")  (url . "/course/signalsandsystemssolution/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "twitter") (icon_pack . "fab")  (name . "Follow")  (url . "/course/signalsandsystemssolution/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "facebook") (icon_pack . "fab")  (name . "Follow")  (url . "/course/signalsandsystemssolution/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "reddit") (icon_pack . "fab")  (name . "Listen")  (url . "/course/signalsandsystemssolution/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "youtube") (icon_pack . "fab")  (name . "Watch it")  (url . "/course/signalsandsystemssolution/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "instagram") (icon_pack . "fab")  (name . "Inst")  (url . "/course/signalsandsystemssolution/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "weibo") (icon_pack . "fab")  (name . "Weibo")  (url . "/course/signalsandsystemssolution/" ) )
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :[links] '( (icon . "wexin") (icon_pack . "fas")  (name . "Wexin")  (url . "/course/signalsandsystemssolution/" ) )
   :END:
 <2020-02-08 Sat 16:58>
