#+FILETAGS:DIARY
#+SETUPFILE: ~/.spacemacs.d/org-templates/diary.org
* 2017
** 2017-11 November
*** 2017-11-22 Wednesday
*** 2017-11-23 Thursday
**** 今日日记
    [2017-11-23 周四 22:30]

    早上，鼎鼎鼻子呼呼响，夏夏说是睡不好的原因。盐水滴鼻子，无效。夏不开心，一方面因为孩子闹，另一方面可能是昨晚在带孩子回郑州看奶奶的安排上发生了分歧，我不开心了。

    夏夏爱我，信任我，在乎我情绪。我不能有恃无恐的不开心，她会好痛苦。我要克制情绪，做好丈夫和父亲的角色。珍惜这信任。

    夏夏稍微有些焦虑，虽然不像她母亲那么严重。但是足以影响她在一些比较糟糕情况下的判断。慌乱和病急乱投医是不可避免的了。

    今天晚上打了羽毛球。回家问夏夏小孩闹不闹，夏夏说都还挺好的。
* 2018
** 2018-02 February
*** 2018-02-11 Sunday
**** CANCELLED org diary
<2018-02-11 Sun>
[2018-02-11 Sun 00:04]
** 2018-03 March
*** 2018-03-14 Wednesday
**** 夏夏要保姆走
<2018-03-14 Wed>
** 2018-04 April
*** 2018-04-07 Saturday
**** 拜见葛阿姨
<2018-04-07 Sat>
[2018-04-07 Sat 17:39]

夏夏妈妈，夏夏和我一同去会见葛阿姨和杨叔叔。杨叔叔 2001 年来到杭州，两年
后葛阿姨也来到杭州，细算已经 17 年有余。期间，风风雨雨。他们在杭州也购置
了多套房产。杨叔叔在浙大经济学院做老师，葛阿姨在拱墅区做公务员。两个人
配合默契，经营有方。这次拜访，妈妈和葛阿姨叙叙旧，聊聊在赣州的老时光，
忆苦思甜。我向杨叔叔请教了人生的方向。最近一段家庭颇不平静，也难安心做
事情。关于工作，杨叔叔帮我分析了两条路上的不同走法。
如果我继续钻研技术，可能的做法是：
1. 45 岁之后做企业顾问；
2. 45 岁之后创业；
3. 在华为内部追求新的技术方向，继续做下去。
如果我要从事政务工作，则可以努力工作，盘活在杭州的人际关系。

关于我和夏夏的家庭结构，杨叔叔的建议是不要两个人都创业，要学会分散风险。
做培训，希望夏夏找到合伙人，做自己最擅长的部分。管理，行政之类工作让最
擅长的人去做。不可能把所有的钱都放到自己口袋里。我应该继续依然是家庭的
财务主力。

这次拜访也是对我所走人生路的一次反思和审视。在杨叔叔和葛阿姨的指点下，
看的更清楚一些。我决定选择在华为换个部门继续干，努力学习 AI。同时要积极
阅读一些趋势相关的书籍，比如《人类简史》，《区块链》。等到下半年拱墅区
再次招聘党政人才储备干部的时候或有帮助。即便此类书籍没有帮助，了解一下
技术的动向，总归无错。

**** 生活随想
<2018-04-07 Sat>
[2018-04-07 Sat 09:24]

今日肖卫平来杭州，我加班，错过了见面机会。

**** 工作随想
[2018-04-07 Sat 09:07]

    昨天去了 nokia 和其中一孙姓主管谈了两个小时。感觉技术上应该没有问题，最
可能出问题的地方在薪资。华为给的工资让外企望尘莫及，同时华为的工作量也
非外企所能比拟。这就是华为的狼性，足够的诱惑，足够的强度，让你追着那只
电兔子不肯放弃。
    诺基亚的工作强度也不低，尤其 5G 项目。大家都在赶着交付，同友商竞争先
机，晚一天可能就是合同的丧失，意味着生存问题。
*** 2018-04-29 Sunday
**** 植物园聚餐
<2018-04-29 Sun>

今天植物园家庭聚餐，山外山饭店，八宝鱼头皇，小牛肉都挺不错。鼎鼎也很开
心。
**** NOKIA 孙先生回话
[2018-04-29 Sun 21:56]

自从 4 月 7 日面试 NOKIA 以来，今天终于有了回话。不知道他们是招不到人，还是
我是备胎。总之，这个算是隔了好久了。我还在面试华为中央硬件研究院传感器
实验室的职位。
