
{{{newline}}}

{{{begin_tip}}}
{{{property(EXPORT_DESCRIPTION)}}}
{{{end_tip}}}


*** Introduction
[2019-12-07 Sat 07:55]

I use hugo before it support Emacs org file. Then I use an Emacs extension
called [[https://github.com/kaushalmodi/ox-hugo][ox-hugo]] which is a carefully crafted Org exporter back-end for Hugo.
Ox-hugo meets all my requirement and definitely worth a try when you are an
advanced user of Emacs Org. By the way, if you are quite familiar with Emacs
Org, there is no need to take time to learn markdown. Emacs Org, I think, is
more elegant than markdown.

*** set up ox-hugo
[2019-12-07 Sat 07:55]

I use Spacemacs and integrate ox-hugo into my config is easy. You can add it
into your private layer or just add it in your =user-config= . Please refer to
[[https://github.com/kaushalmodi/ox-hugo][the repo.]] and read the document for more information.

The first time you want to export an Org file or a subtree of an Org file, use
=M-x org-hugo-export-to-md= . There will be a hugo-related section in the
=org-dispatcher= whenever you use =C-c C-e= .
*** use Org Macro replacement
[2019-12-07 Sat 08:04]

Often, you want different actions when you export the Org file to
hugo-compatible markdown and latex file. For example, hugo or hugo theme supports
summary and shortcodes such as =alert note= and =alert warning= (see  [[https://sourcethemes.com/academic/docs/writing-markdown-latex/][Writing
content with Markdown, LaTeX, and Shortcodes | Academic]] )

When you export the snippet to markdown then hugo will display the content
according to the css. However, latex does not recognize the shortcodes. So latex
will display ={ {% alert note %} }= literally which is clutter. The Org Macro may
help. For more information please refer to [[https://orgmode.org/manual/Macro-replacement.html][The Org Manual: Macro replacement]] and
[[https://github.com/fniessen/org-macros][fniessen/org-macros: Shared macros for Org mode]] . I also define my own Org Macro
in [[https://github.com/msteamc/.spacemacs.d/blob/master/org-templates/enpost.org][my setup file for every .org file]]. With Org Macro, I control some contents
and options exist only for certain backend.

Once you are familiar with Org Macro, It behaves beyond your imagination.
*** use the setupfile for each Org file
[2019-12-07 Sat 16:17]

Often, you options for a org file grows more and more. If you think it kind of
clutter at the top of your Org files, you can group them in a setupfile then
include it at the top of your Org file.

For my setupfiles, please refer to [[https://github.com/msteamc/.spacemacs.d/tree/master/org-templates][my org-templates]]. As you can see, I have
several setupfiles for different aims. To include one of them in my Org file, I
use:

=#+SETUPFILE: <path+name of the setup files>=

By using =#+SETUPFILE= ,I only have to option lines at the top of my org file.
So it looks clean.

Also, you can notice that in [[https://github.com/msteamc/.spacemacs.d/blob/master/org-templates/enpost.org][my setupfile named enpost.org]] exists options for
different export targets.
